AWSTemplateFormatVersion: "2010-09-09"
Description: "Scale Out"
Resources:
  JatinInstan1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09a41e26df464c548
      AvailabilityZone: us-east-1a
      KeyName: JatinKeyPair
      Tags:
        - Key: User
          Value: Jatin.x
  JatinLaunchInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-09a41e26df464c548
        KeyName: JatinKeyPair
      LaunchTemplateName: LaunchTemplate
  JatinAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: JATIN123
      AvailabilityZones:
        - us-east-1a
      LaunchTemplate:
          LaunchTemplateName: JatinLaunchTemplate
          Version: !GetAtt JatinLaunchInstance.LatestVersionNumber
      MaxSize: 3
      MinSize: 1
      DesiredCapacity: 2
  JatinAlram:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      ComparisonOperator: LessThanLowerOrGreaterThanUpperThreshold
      EvaluationPeriods: 2
      Metrics:
        MetricStat:
          Metric:
            MetricName: Invocations
            Namespace: AWS/Lambda
          Period: 30
          Stat: Sum
      ThresholdMetricId: 30
  JationScailingPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AutoScalingGroupName: !Ref JatinAutoScalingGroup
      PolicyType: PredictiveScaling
      PredictiveScalingConfiguration:
        MetricSpecifications:
          - TargetValue: '70'
            PredefinedMetricPairSpecification:
              PredefinedMetricType: ASGCPUUtilization
        Mode: ForecastOnly